// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/helloworld.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Gender int32

const (
	Gender_GENDER_UNKNOWN Gender = 0
	Gender_GENDER_MALE    Gender = 1
	Gender_GENDER_FEMALE  Gender = 2
)

var Gender_name = map[int32]string{
	0: "GENDER_UNKNOWN",
	1: "GENDER_MALE",
	2: "GENDER_FEMALE",
}

var Gender_value = map[string]int32{
	"GENDER_UNKNOWN": 0,
	"GENDER_MALE":    1,
	"GENDER_FEMALE":  2,
}

func (x Gender) String() string {
	return proto.EnumName(Gender_name, int32(x))
}

func (Gender) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4d53fe9c48eadaad, []int{0}
}

type Person struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age                  int32    `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Person) Reset()         { *m = Person{} }
func (m *Person) String() string { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()    {}
func (*Person) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d53fe9c48eadaad, []int{0}
}

func (m *Person) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person.Unmarshal(m, b)
}
func (m *Person) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person.Marshal(b, m, deterministic)
}
func (m *Person) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person.Merge(m, src)
}
func (m *Person) XXX_Size() int {
	return xxx_messageInfo_Person.Size(m)
}
func (m *Person) XXX_DiscardUnknown() {
	xxx_messageInfo_Person.DiscardUnknown(m)
}

var xxx_messageInfo_Person proto.InternalMessageInfo

func (m *Person) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Person) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

type HelloRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Items                []string `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	Gender               Gender   `protobuf:"varint,3,opt,name=gender,proto3,enum=helloworld.Gender" json:"gender,omitempty"`
	Person               *Person  `protobuf:"bytes,4,opt,name=person,proto3" json:"person,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d53fe9c48eadaad, []int{1}
}

func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (m *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(m, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *HelloRequest) GetItems() []string {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *HelloRequest) GetGender() Gender {
	if m != nil {
		return m.Gender
	}
	return Gender_GENDER_UNKNOWN
}

func (m *HelloRequest) GetPerson() *Person {
	if m != nil {
		return m.Person
	}
	return nil
}

type HelloReply struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Items                []string `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	Gender               Gender   `protobuf:"varint,3,opt,name=gender,proto3,enum=helloworld.Gender" json:"gender,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloReply) Reset()         { *m = HelloReply{} }
func (m *HelloReply) String() string { return proto.CompactTextString(m) }
func (*HelloReply) ProtoMessage()    {}
func (*HelloReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d53fe9c48eadaad, []int{2}
}

func (m *HelloReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloReply.Unmarshal(m, b)
}
func (m *HelloReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloReply.Marshal(b, m, deterministic)
}
func (m *HelloReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloReply.Merge(m, src)
}
func (m *HelloReply) XXX_Size() int {
	return xxx_messageInfo_HelloReply.Size(m)
}
func (m *HelloReply) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloReply.DiscardUnknown(m)
}

var xxx_messageInfo_HelloReply proto.InternalMessageInfo

func (m *HelloReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *HelloReply) GetItems() []string {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *HelloReply) GetGender() Gender {
	if m != nil {
		return m.Gender
	}
	return Gender_GENDER_UNKNOWN
}

type PlusRequest struct {
	A                    int64    `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
	B                    int64    `protobuf:"varint,2,opt,name=b,proto3" json:"b,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlusRequest) Reset()         { *m = PlusRequest{} }
func (m *PlusRequest) String() string { return proto.CompactTextString(m) }
func (*PlusRequest) ProtoMessage()    {}
func (*PlusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d53fe9c48eadaad, []int{3}
}

func (m *PlusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlusRequest.Unmarshal(m, b)
}
func (m *PlusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlusRequest.Marshal(b, m, deterministic)
}
func (m *PlusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlusRequest.Merge(m, src)
}
func (m *PlusRequest) XXX_Size() int {
	return xxx_messageInfo_PlusRequest.Size(m)
}
func (m *PlusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PlusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PlusRequest proto.InternalMessageInfo

func (m *PlusRequest) GetA() int64 {
	if m != nil {
		return m.A
	}
	return 0
}

func (m *PlusRequest) GetB() int64 {
	if m != nil {
		return m.B
	}
	return 0
}

type PlusReply struct {
	Result               int64    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlusReply) Reset()         { *m = PlusReply{} }
func (m *PlusReply) String() string { return proto.CompactTextString(m) }
func (*PlusReply) ProtoMessage()    {}
func (*PlusReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d53fe9c48eadaad, []int{4}
}

func (m *PlusReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlusReply.Unmarshal(m, b)
}
func (m *PlusReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlusReply.Marshal(b, m, deterministic)
}
func (m *PlusReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlusReply.Merge(m, src)
}
func (m *PlusReply) XXX_Size() int {
	return xxx_messageInfo_PlusReply.Size(m)
}
func (m *PlusReply) XXX_DiscardUnknown() {
	xxx_messageInfo_PlusReply.DiscardUnknown(m)
}

var xxx_messageInfo_PlusReply proto.InternalMessageInfo

func (m *PlusReply) GetResult() int64 {
	if m != nil {
		return m.Result
	}
	return 0
}

func init() {
	proto.RegisterEnum("helloworld.Gender", Gender_name, Gender_value)
	proto.RegisterType((*Person)(nil), "helloworld.Person")
	proto.RegisterType((*HelloRequest)(nil), "helloworld.HelloRequest")
	proto.RegisterType((*HelloReply)(nil), "helloworld.HelloReply")
	proto.RegisterType((*PlusRequest)(nil), "helloworld.PlusRequest")
	proto.RegisterType((*PlusReply)(nil), "helloworld.PlusReply")
}

func init() { proto.RegisterFile("proto/helloworld.proto", fileDescriptor_4d53fe9c48eadaad) }

var fileDescriptor_4d53fe9c48eadaad = []byte{
	// 404 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x93, 0x41, 0xaf, 0xd2, 0x40,
	0x10, 0xc7, 0xdf, 0x52, 0x5e, 0xb1, 0xc3, 0x7b, 0xcf, 0x3a, 0x51, 0x6c, 0xde, 0xa9, 0xa9, 0x97,
	0xfa, 0x0e, 0x7d, 0x04, 0x2f, 0x9e, 0x8c, 0x18, 0x6a, 0x89, 0x4a, 0x25, 0x6b, 0x8c, 0x89, 0x17,
	0x53, 0xc2, 0x08, 0x24, 0x0b, 0x2d, 0xdb, 0x36, 0xa6, 0xdf, 0xc2, 0x0f, 0xe2, 0x87, 0x34, 0xdd,
	0x2e, 0x01, 0x94, 0x8b, 0x78, 0xea, 0xce, 0xec, 0x7f, 0xfe, 0xf3, 0x9b, 0xd9, 0x14, 0x7a, 0x99,
	0x4c, 0x8b, 0xf4, 0x7e, 0x49, 0x42, 0xa4, 0x3f, 0x52, 0x29, 0xe6, 0x81, 0x4a, 0x20, 0xec, 0x33,
	0x5e, 0x00, 0xe6, 0x94, 0x64, 0x9e, 0x6e, 0x10, 0xa1, 0xbd, 0x49, 0xd6, 0xe4, 0x30, 0x97, 0xf9,
	0x16, 0x57, 0x67, 0xb4, 0xc1, 0x48, 0x16, 0xe4, 0xb4, 0x5c, 0xe6, 0x5f, 0xf2, 0xfa, 0xe8, 0xfd,
	0x64, 0x70, 0x35, 0xae, 0xcb, 0x39, 0x6d, 0x4b, 0xca, 0x8b, 0x93, 0x65, 0x8f, 0xe1, 0x72, 0x55,
	0xd0, 0x3a, 0x77, 0x5a, 0xae, 0xe1, 0x5b, 0xbc, 0x09, 0xf0, 0x0e, 0xcc, 0x05, 0x6d, 0xe6, 0x24,
	0x1d, 0xc3, 0x65, 0xfe, 0xcd, 0x00, 0x83, 0x03, 0xb2, 0x48, 0xdd, 0x70, 0xad, 0xa8, 0xb5, 0x99,
	0xc2, 0x72, 0xda, 0x2e, 0xf3, 0xbb, 0xc7, 0xda, 0x06, 0x98, 0x6b, 0x85, 0xb7, 0x04, 0xd0, 0x44,
	0x99, 0xa8, 0xd0, 0x81, 0xce, 0x9a, 0xf2, 0xbc, 0xc6, 0x6e, 0x90, 0x76, 0xe1, 0xff, 0x53, 0x79,
	0xcf, 0xa1, 0x3b, 0x15, 0x65, 0xbe, 0x1b, 0xfd, 0x0a, 0x58, 0xa2, 0x9a, 0x18, 0x9c, 0x25, 0x75,
	0x34, 0x53, 0x9b, 0x32, 0x38, 0x9b, 0x79, 0xcf, 0xc0, 0x6a, 0xa4, 0x35, 0x53, 0x0f, 0x4c, 0x49,
	0x79, 0x29, 0x0a, 0xad, 0xd6, 0xd1, 0xdd, 0x6b, 0x30, 0x9b, 0x0e, 0x88, 0x70, 0x13, 0x85, 0xf1,
	0x28, 0xe4, 0xdf, 0x3e, 0xc7, 0xef, 0xe3, 0x8f, 0x5f, 0x62, 0xfb, 0x02, 0x1f, 0x42, 0x57, 0xe7,
	0x26, 0xc3, 0x0f, 0xa1, 0xcd, 0xf0, 0x11, 0x5c, 0xeb, 0xc4, 0xdb, 0x50, 0xa5, 0x5a, 0x83, 0x5f,
	0x06, 0x74, 0x22, 0x49, 0x54, 0x90, 0xc4, 0x57, 0xf0, 0xe0, 0x53, 0x52, 0xa9, 0x55, 0xa0, 0x73,
	0x38, 0xc5, 0xe1, 0x7b, 0xdd, 0xf6, 0x4e, 0xdc, 0x64, 0xa2, 0xf2, 0x2e, 0xf0, 0x25, 0xb4, 0x6b,
	0x64, 0x7c, 0x7a, 0xb4, 0xeb, 0xfd, 0xbc, 0xb7, 0x4f, 0xfe, 0xbe, 0x68, 0x2a, 0xc7, 0x80, 0xbb,
	0xce, 0xc3, 0xef, 0x05, 0xc9, 0x11, 0x89, 0xa4, 0x3a, 0x8b, 0xe1, 0xdd, 0xde, 0x69, 0x52, 0x8a,
	0x62, 0xa5, 0xdf, 0xf4, 0xdf, 0x9d, 0xfa, 0x0c, 0xc7, 0x60, 0xff, 0xe1, 0xb5, 0x3d, 0xc7, 0xc9,
	0x67, 0x18, 0xc1, 0xf5, 0x91, 0xd3, 0x79, 0x36, 0x7d, 0xf6, 0xc6, 0xfa, 0xda, 0x09, 0xee, 0xd5,
	0x4f, 0x38, 0x33, 0xd5, 0xe7, 0xc5, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x95, 0xe3, 0xed, 0x6b,
	0xa5, 0x03, 0x00, 0x00,
}
