// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/helloworld.proto

package helloworld

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type HelloRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d53fe9c48eadaad, []int{0}
}

func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (m *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(m, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type HelloReply struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloReply) Reset()         { *m = HelloReply{} }
func (m *HelloReply) String() string { return proto.CompactTextString(m) }
func (*HelloReply) ProtoMessage()    {}
func (*HelloReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d53fe9c48eadaad, []int{1}
}

func (m *HelloReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloReply.Unmarshal(m, b)
}
func (m *HelloReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloReply.Marshal(b, m, deterministic)
}
func (m *HelloReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloReply.Merge(m, src)
}
func (m *HelloReply) XXX_Size() int {
	return xxx_messageInfo_HelloReply.Size(m)
}
func (m *HelloReply) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloReply.DiscardUnknown(m)
}

var xxx_messageInfo_HelloReply proto.InternalMessageInfo

func (m *HelloReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type PlusRequest struct {
	A                    int64    `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
	B                    int64    `protobuf:"varint,2,opt,name=b,proto3" json:"b,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlusRequest) Reset()         { *m = PlusRequest{} }
func (m *PlusRequest) String() string { return proto.CompactTextString(m) }
func (*PlusRequest) ProtoMessage()    {}
func (*PlusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d53fe9c48eadaad, []int{2}
}

func (m *PlusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlusRequest.Unmarshal(m, b)
}
func (m *PlusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlusRequest.Marshal(b, m, deterministic)
}
func (m *PlusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlusRequest.Merge(m, src)
}
func (m *PlusRequest) XXX_Size() int {
	return xxx_messageInfo_PlusRequest.Size(m)
}
func (m *PlusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PlusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PlusRequest proto.InternalMessageInfo

func (m *PlusRequest) GetA() int64 {
	if m != nil {
		return m.A
	}
	return 0
}

func (m *PlusRequest) GetB() int64 {
	if m != nil {
		return m.B
	}
	return 0
}

type PlusReply struct {
	Result               int64    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlusReply) Reset()         { *m = PlusReply{} }
func (m *PlusReply) String() string { return proto.CompactTextString(m) }
func (*PlusReply) ProtoMessage()    {}
func (*PlusReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d53fe9c48eadaad, []int{3}
}

func (m *PlusReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlusReply.Unmarshal(m, b)
}
func (m *PlusReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlusReply.Marshal(b, m, deterministic)
}
func (m *PlusReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlusReply.Merge(m, src)
}
func (m *PlusReply) XXX_Size() int {
	return xxx_messageInfo_PlusReply.Size(m)
}
func (m *PlusReply) XXX_DiscardUnknown() {
	xxx_messageInfo_PlusReply.DiscardUnknown(m)
}

var xxx_messageInfo_PlusReply proto.InternalMessageInfo

func (m *PlusReply) GetResult() int64 {
	if m != nil {
		return m.Result
	}
	return 0
}

type BotRequest struct {
	Appid                int64    `protobuf:"varint,1,opt,name=appid,proto3" json:"appid,omitempty"`
	Host                 string   `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Sdkflag              int32    `protobuf:"varint,3,opt,name=sdkflag,proto3" json:"sdkflag,omitempty"`
	Ip                   string   `protobuf:"bytes,4,opt,name=ip,proto3" json:"ip,omitempty"`
	Url                  []byte   `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`
	Cookie               []byte   `protobuf:"bytes,6,opt,name=cookie,proto3" json:"cookie,omitempty"`
	Getform              []byte   `protobuf:"bytes,7,opt,name=getform,proto3" json:"getform,omitempty"`
	Postform             []byte   `protobuf:"bytes,8,opt,name=postform,proto3" json:"postform,omitempty"`
	Postsdkform          []byte   `protobuf:"bytes,9,opt,name=postsdkform,proto3" json:"postsdkform,omitempty"`
	Sign                 []byte   `protobuf:"bytes,10,opt,name=sign,proto3" json:"sign,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BotRequest) Reset()         { *m = BotRequest{} }
func (m *BotRequest) String() string { return proto.CompactTextString(m) }
func (*BotRequest) ProtoMessage()    {}
func (*BotRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d53fe9c48eadaad, []int{4}
}

func (m *BotRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BotRequest.Unmarshal(m, b)
}
func (m *BotRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BotRequest.Marshal(b, m, deterministic)
}
func (m *BotRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BotRequest.Merge(m, src)
}
func (m *BotRequest) XXX_Size() int {
	return xxx_messageInfo_BotRequest.Size(m)
}
func (m *BotRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BotRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BotRequest proto.InternalMessageInfo

func (m *BotRequest) GetAppid() int64 {
	if m != nil {
		return m.Appid
	}
	return 0
}

func (m *BotRequest) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *BotRequest) GetSdkflag() int32 {
	if m != nil {
		return m.Sdkflag
	}
	return 0
}

func (m *BotRequest) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *BotRequest) GetUrl() []byte {
	if m != nil {
		return m.Url
	}
	return nil
}

func (m *BotRequest) GetCookie() []byte {
	if m != nil {
		return m.Cookie
	}
	return nil
}

func (m *BotRequest) GetGetform() []byte {
	if m != nil {
		return m.Getform
	}
	return nil
}

func (m *BotRequest) GetPostform() []byte {
	if m != nil {
		return m.Postform
	}
	return nil
}

func (m *BotRequest) GetPostsdkform() []byte {
	if m != nil {
		return m.Postsdkform
	}
	return nil
}

func (m *BotRequest) GetSign() []byte {
	if m != nil {
		return m.Sign
	}
	return nil
}

type BotResponse struct {
	Ret                  int32    `protobuf:"varint,1,opt,name=ret,proto3" json:"ret,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Session              string   `protobuf:"bytes,3,opt,name=session,proto3" json:"session,omitempty"`
	Ts                   int32    `protobuf:"varint,4,opt,name=ts,proto3" json:"ts,omitempty"`
	Token                string   `protobuf:"bytes,5,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BotResponse) Reset()         { *m = BotResponse{} }
func (m *BotResponse) String() string { return proto.CompactTextString(m) }
func (*BotResponse) ProtoMessage()    {}
func (*BotResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4d53fe9c48eadaad, []int{5}
}

func (m *BotResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BotResponse.Unmarshal(m, b)
}
func (m *BotResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BotResponse.Marshal(b, m, deterministic)
}
func (m *BotResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BotResponse.Merge(m, src)
}
func (m *BotResponse) XXX_Size() int {
	return xxx_messageInfo_BotResponse.Size(m)
}
func (m *BotResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BotResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BotResponse proto.InternalMessageInfo

func (m *BotResponse) GetRet() int32 {
	if m != nil {
		return m.Ret
	}
	return 0
}

func (m *BotResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BotResponse) GetSession() string {
	if m != nil {
		return m.Session
	}
	return ""
}

func (m *BotResponse) GetTs() int32 {
	if m != nil {
		return m.Ts
	}
	return 0
}

func (m *BotResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "helloworld.HelloRequest")
	proto.RegisterType((*HelloReply)(nil), "helloworld.HelloReply")
	proto.RegisterType((*PlusRequest)(nil), "helloworld.PlusRequest")
	proto.RegisterType((*PlusReply)(nil), "helloworld.PlusReply")
	proto.RegisterType((*BotRequest)(nil), "helloworld.BotRequest")
	proto.RegisterType((*BotResponse)(nil), "helloworld.BotResponse")
}

func init() { proto.RegisterFile("proto/helloworld.proto", fileDescriptor_4d53fe9c48eadaad) }

var fileDescriptor_4d53fe9c48eadaad = []byte{
	// 432 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0xc1, 0x8e, 0xd3, 0x30,
	0x10, 0xdd, 0xa4, 0x4d, 0xdb, 0x4c, 0x2b, 0x40, 0x16, 0x74, 0xad, 0x9e, 0xaa, 0x20, 0xa1, 0x72,
	0x59, 0x24, 0xb8, 0x70, 0x42, 0x62, 0x59, 0x89, 0x3d, 0xae, 0xcc, 0x17, 0xb8, 0xdb, 0x69, 0x1b,
	0xd5, 0x8d, 0x8d, 0xed, 0x0a, 0xe5, 0x3b, 0xf8, 0x57, 0xce, 0x68, 0x26, 0xc9, 0x36, 0xa8, 0x9c,
	0xf6, 0x36, 0x6f, 0xde, 0xcb, 0x78, 0xde, 0xcc, 0x04, 0xe6, 0xce, 0xdb, 0x68, 0x3f, 0xec, 0xd1,
	0x18, 0xfb, 0xcb, 0x7a, 0xb3, 0xb9, 0xe1, 0x84, 0x80, 0x73, 0xa6, 0x28, 0x60, 0x76, 0x4f, 0x48,
	0xe1, 0xcf, 0x13, 0x86, 0x28, 0x04, 0x0c, 0x2b, 0x7d, 0x44, 0x99, 0x2c, 0x93, 0x55, 0xae, 0x38,
	0x2e, 0xde, 0x01, 0xb4, 0x1a, 0x67, 0x6a, 0x21, 0x61, 0x7c, 0xc4, 0x10, 0xf4, 0xae, 0x13, 0x75,
	0xb0, 0x78, 0x0f, 0xd3, 0x07, 0x73, 0x0a, 0x5d, 0xa9, 0x19, 0x24, 0x9a, 0x25, 0x03, 0x95, 0x68,
	0x42, 0x6b, 0x99, 0x36, 0x68, 0x5d, 0xbc, 0x85, 0xbc, 0x91, 0x52, 0xc5, 0x39, 0x8c, 0x3c, 0x86,
	0x93, 0x89, 0xad, 0xba, 0x45, 0xc5, 0x9f, 0x04, 0xe0, 0xd6, 0xc6, 0xae, 0xde, 0x6b, 0xc8, 0xb4,
	0x73, 0xe5, 0xa6, 0x55, 0x35, 0x80, 0x1a, 0xde, 0xdb, 0x10, 0xb9, 0x74, 0xae, 0x38, 0xa6, 0x16,
	0xc3, 0xe6, 0xb0, 0x35, 0x7a, 0x27, 0x07, 0xcb, 0x64, 0x95, 0xa9, 0x0e, 0x8a, 0x17, 0x90, 0x96,
	0x4e, 0x0e, 0x59, 0x9b, 0x96, 0x4e, 0xbc, 0x82, 0xc1, 0xc9, 0x1b, 0x99, 0x2d, 0x93, 0xd5, 0x4c,
	0x51, 0x48, 0xcd, 0x3c, 0x5a, 0x7b, 0x28, 0x51, 0x8e, 0x38, 0xd9, 0x22, 0xaa, 0xb9, 0xc3, 0xb8,
	0xb5, 0xfe, 0x28, 0xc7, 0x4c, 0x74, 0x50, 0x2c, 0x60, 0xe2, 0x6c, 0x68, 0xa8, 0x09, 0x53, 0x4f,
	0x58, 0x2c, 0x61, 0x4a, 0x31, 0x3d, 0x4f, 0x74, 0xce, 0x74, 0x3f, 0x45, 0xfd, 0x87, 0x72, 0x57,
	0x49, 0x60, 0x8a, 0xe3, 0x22, 0xc0, 0x94, 0x7d, 0x07, 0x67, 0xab, 0x80, 0xd4, 0xa4, 0xc7, 0x66,
	0x38, 0x99, 0xa2, 0xf0, 0x69, 0x4b, 0xe9, 0x79, 0x4b, 0x6c, 0x1a, 0x43, 0x28, 0x6d, 0xc5, 0xa6,
	0x73, 0xd5, 0x41, 0x32, 0x1d, 0x03, 0x9b, 0xce, 0x54, 0x1a, 0x03, 0x0d, 0x32, 0xda, 0x03, 0x56,
	0x6c, 0x3b, 0x57, 0x0d, 0xf8, 0xf8, 0x3b, 0x85, 0xf1, 0x77, 0x8f, 0x18, 0xd1, 0x8b, 0x2f, 0x30,
	0xf9, 0xa1, 0x6b, 0x5e, 0xba, 0x90, 0x37, 0xbd, 0x03, 0xea, 0xdf, 0xca, 0x62, 0xfe, 0x1f, 0xc6,
	0x99, 0xba, 0xb8, 0x12, 0x9f, 0x61, 0x48, 0xeb, 0x15, 0xd7, 0x7d, 0x45, 0xef, 0x36, 0x16, 0x6f,
	0x2e, 0x89, 0xe6, 0xcb, 0x7b, 0x10, 0xdd, 0xcb, 0x5f, 0xb7, 0x11, 0xfd, 0x1d, 0x1a, 0x5d, 0x3f,
	0xab, 0x87, 0x3b, 0x78, 0x79, 0x6b, 0xe3, 0x83, 0xae, 0x8d, 0xd5, 0x9b, 0x6f, 0x7b, 0x7c, 0x3c,
	0x88, 0x7f, 0xc4, 0xe7, 0xcb, 0x5a, 0x5c, 0x5f, 0xe4, 0x9b, 0xc9, 0x17, 0x57, 0xeb, 0x11, 0xff,
	0x32, 0x9f, 0xfe, 0x06, 0x00, 0x00, 0xff, 0xff, 0x73, 0xab, 0x91, 0x21, 0x4c, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GreeterClient is the client API for Greeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GreeterClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
	Plus(ctx context.Context, in *PlusRequest, opts ...grpc.CallOption) (*PlusReply, error)
	SayHelloAfterDelay(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
	BotPayloadCheck(ctx context.Context, in *BotRequest, opts ...grpc.CallOption) (*BotResponse, error)
}

type greeterClient struct {
	cc *grpc.ClientConn
}

func NewGreeterClient(cc *grpc.ClientConn) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/helloworld.Greeter/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) Plus(ctx context.Context, in *PlusRequest, opts ...grpc.CallOption) (*PlusReply, error) {
	out := new(PlusReply)
	err := c.cc.Invoke(ctx, "/helloworld.Greeter/Plus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) SayHelloAfterDelay(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/helloworld.Greeter/SayHelloAfterDelay", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) BotPayloadCheck(ctx context.Context, in *BotRequest, opts ...grpc.CallOption) (*BotResponse, error) {
	out := new(BotResponse)
	err := c.cc.Invoke(ctx, "/helloworld.Greeter/BotPayloadCheck", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GreeterServer is the server API for Greeter service.
type GreeterServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	Plus(context.Context, *PlusRequest) (*PlusReply, error)
	SayHelloAfterDelay(context.Context, *HelloRequest) (*HelloReply, error)
	BotPayloadCheck(context.Context, *BotRequest) (*BotResponse, error)
}

// UnimplementedGreeterServer can be embedded to have forward compatible implementations.
type UnimplementedGreeterServer struct {
}

func (*UnimplementedGreeterServer) SayHello(ctx context.Context, req *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (*UnimplementedGreeterServer) Plus(ctx context.Context, req *PlusRequest) (*PlusReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Plus not implemented")
}
func (*UnimplementedGreeterServer) SayHelloAfterDelay(ctx context.Context, req *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHelloAfterDelay not implemented")
}
func (*UnimplementedGreeterServer) BotPayloadCheck(ctx context.Context, req *BotRequest) (*BotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BotPayloadCheck not implemented")
}

func RegisterGreeterServer(s *grpc.Server, srv GreeterServer) {
	s.RegisterService(&_Greeter_serviceDesc, srv)
}

func _Greeter_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/helloworld.Greeter/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_Plus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).Plus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/helloworld.Greeter/Plus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).Plus(ctx, req.(*PlusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_SayHelloAfterDelay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).SayHelloAfterDelay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/helloworld.Greeter/SayHelloAfterDelay",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).SayHelloAfterDelay(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_BotPayloadCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).BotPayloadCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/helloworld.Greeter/BotPayloadCheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).BotPayloadCheck(ctx, req.(*BotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Greeter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "helloworld.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Greeter_SayHello_Handler,
		},
		{
			MethodName: "Plus",
			Handler:    _Greeter_Plus_Handler,
		},
		{
			MethodName: "SayHelloAfterDelay",
			Handler:    _Greeter_SayHelloAfterDelay_Handler,
		},
		{
			MethodName: "BotPayloadCheck",
			Handler:    _Greeter_BotPayloadCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/helloworld.proto",
}
